vich_uploader:
  db_driver: orm

  mappings:
    drivingSchoolLogo:
      uri_prefix: /images/drivingSchool/logos
      upload_destination: '%kernel.project_dir%/public/images/drivingSchool/logos'
      namer:
        service: Vich\UploaderBundle\Naming\HashNamer