version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=docker@test.com
      - PGADMIN_DEFAULT_PASSWORD=docker
      - PGADMIN_LISTEN_POST=5050
    ports:
      - "5050:80"
    depends_on:
      - database
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
